Repository VadymSula/mafia-helper, pull requests merged in 2020-02, with the labels that each got.

#21 #16 add: create entities
  src/main/java/org/deanoffice2/mafiahelper/entity/CheckGame.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
Labels: back-end, enhancement, must

#22 15 feat/make up page
  game.html
  game2.html
  style/game.css
Labels: front-end(styles), must

#25 #23 add: add Swagger configuration
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/deanoffice2/mafiahelper/config/SwaggerConfig.java
Labels: back-end, should
