Repository VadymSula/mafia-helper, pull requests merged in 2020-06, with the labels that each got.

#106 85 fix/make up history game
  history-game.html
  images/historyGame/joystic-icons.jpg
  style/history_game.css
Labels: enhancement, front-end(styles), should

#118 117 feat/add history games
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/ChecksResultRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameService.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
Labels: back-end, enhancement, must

#121 120 fix/fix missed columns
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/controller/StaticDataController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/Player.java
  src/main/java/org/deanoffice2/mafiahelper/entity/RatingGame.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticService.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticServiceImpl.java
  src/main/resources/db/migration/V3_20_04_2020__create_player_table.sql
  src/main/resources/db/migration/V5_11_04_2020__create_game_table.sql
  src/main/resources/db/migration/V8_22_04_2020__create_rating_table.sql
Labels: back-end, bug, must
