Repository VadymSula/mafia-helper, pull requests merged in 2020-03, with the labels that each got.

#29 28 feat/get info about the game
  build.gradle
  src/main/java/org/deanoffice2/mafiahelper/MainApplication.java
  src/main/java/org/deanoffice2/mafiahelper/controller/Controller.java
  src/main/java/org/deanoffice2/mafiahelper/entity/CheckGame.java
  src/main/java/org/deanoffice2/mafiahelper/entity/DomainObject.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameService.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
Labels: back-end, should

#37 31 feat/add result game to database
  build.gradle
  src/main/java/org/deanoffice2/mafiahelper/controller/Controller.java
  src/main/java/org/deanoffice2/mafiahelper/entity/CheckGame.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameService.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
Labels: back-end, enhancement, must

#41 40 refactor/change enhance repository
  src/main/java/org/deanoffice2/mafiahelper/controller/Controller.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/ChecksResultRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameService.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
Labels: back-end, could, enhancement

#24 3 fix/make up home page
  images/icons_general/icon-play.png
  images/icons_general/icon_book.png
  images/icons_general/icon_medal.png
  images/icons_general/icon_ul.png
  index.html
  style/index_style.css
Labels: front-end(styles), must

#47 #9 add: timer controller
  src/components/game/game.css
  src/components/game/inGame/inGame.tsx
Labels: enhancement, front-end(JS), front-end(styles), must

#48 #8 add: added distributes roles for players
  src/components/game/setPlayers/renderPlayer.tsx
  src/components/game/setPlayers/setPlayers.tsx
Labels: enhancement, front-end(JS), must

#50 #7 add: start the game
  src/components/game/game.tsx
Labels: enhancement, front-end(JS), front-end(styles), must

#51 #49 add: configurations for React
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Modals/addPlayer.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/models/player.ts
  src/react-app-env.d.ts
  src/serviceWorker.ts
  src/setupTests.ts
  src/store/actions.tsx
  src/store/redusers.tsx
  tsconfig.json
Labels: front-end(JS), good first issue, must

#52 #10 add: can set folls, voting, shooting and checks
  src/App.tsx
  src/components/game/game.css
  src/components/game/inGame/inGame.tsx
  src/components/game/inGame/modal.css
  src/components/game/inGame/playerDiv.tsx
  src/models/modal.css
  src/models/modal.tsx
  src/store/actions.tsx
  src/store/redusers.tsx
Labels: enhancement, front-end(JS), front-end(styles), should

#53 43 feat/make up result game page
  images/resultGame/mafiaWin.png
  images/resultGame/townWin.png
  result_game.html
  style/result_game.css
Labels: enhancement, front-end(styles), should

#55 46 feat/get info about end game
  src/main/java/org/deanoffice2/mafiahelper/controller/Controller.java
  src/main/java/org/deanoffice2/mafiahelper/entity/CheckGame.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/ChecksResultRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameListRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameService.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
Labels: back-end, enhancement, must

#58 57 fix/reload page error
  public/_redirects
Labels: front-end(JS)

#59 56 fix/timer in game page
  src/components/game/inGame/inGame.tsx
  src/components/game/inGame/playerDiv.tsx
Labels: bug, front-end(JS), must

#60 20 enhance/create exception handler
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/exceptions/DataNotFoundException.java
  src/main/java/org/deanoffice2/mafiahelper/exceptions/ForbiddenException.java
  src/main/java/org/deanoffice2/mafiahelper/exceptions/IllegalInputDataException.java
  src/main/java/org/deanoffice2/mafiahelper/exceptions/UnauthorizedException.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
Labels: back-end, could, enhancement
