Repository VadymSula/mafia-helper, pull requests merged in 2020-04, with the labels that each got.

#33 6 test/test nastia
  guides.html
  images/icons_guides/icons_people.png
  images/icons_guides/smile-1.png
  style/guides_style.css
Labels: front-end(styles), must

#61 44 add/add info about game
  src/components/Modals/addPlayer.tsx
  src/components/game/inGame/inGame.tsx
  src/components/game/inGame/playerDiv.tsx
  src/servise/apiServise.ts
  src/store/actions.tsx
  src/store/redusers.tsx
Labels: enhancement, front-end(JS), should

#69 63 add/add main page to react
  game.html
  game2.html
  index.html
  src/App.tsx
  src/assets/mafia.png
  src/components/MainPage/mainPage.css
  src/components/MainPage/mainPage.tsx
  src/components/game/game.css
  src/components/game/game.tsx
  src/components/game/inGame/inGame.tsx
  src/models/modal.css
  src/models/modal.tsx
  src/models/player.ts
  src/store/redusers.tsx
Labels: front-end(JS), must

#70 #62 add: transfer page to react
  .gitignore
  result_game.html
  src/App.tsx
  src/assets/icons_people.png
  src/assets/smile-1.png
  src/components/GuidesPage/guidesPage.css
  src/components/GuidesPage/guidesPage.tsx
  src/components/MainPage/mainPage.tsx
Labels: front-end(JS), must

#72 #65 fix: fixed don`t correct view
  src/components/game/game.css
  src/components/game/inGame/inGame.tsx
Labels: bug, front-end(JS), must

#82 77 enhance/add flyway configurations
  build.gradle
  src/main/java/org/deanoffice2/mafiahelper/exceptions/IllegalInputDataException.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1_11_04_2020__create_game_table.sql
  src/main/resources/db/migration/V2_11_04_2020__create_player_result_table.sql
  src/main/resources/db/migration/V3_11_04_2020__create_checks_table.sql
Labels: back-end, must

#84 83 feat/lead can set roles
  src/main/java/org/deanoffice2/mafiahelper/config/DatabaseConfig.java
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/controller/StaticDataController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticService.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticServiceImpl.java
  src/main/resources/db/migration/V1_11_04_2020__create_game_table.sql
  src/main/resources/db/migration/V2_11_04_2020__create_player_result_table.sql
  src/main/resources/db/migration/V4_14_04_2020__create_role_table.sql
  src/main/resources/db/migration/V5_14_04_2020__insert_roles.sql
Labels: back-end, enhancement, should

#86 75 feat/add new player or select with list
  src/main/java/org/deanoffice2/mafiahelper/controller/StaticDataController.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticService.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticServiceImpl.java
  src/main/resources/db/migration/V2_11_04_2020__create_player_result_table.sql
  src/main/resources/db/migration/V6_20_04_2020__create_player_table.sql
Labels: back-end, enhancement, should

#87 83 feat/lead can set roles front
  src/App.tsx
  src/components/GuidesPage/guidesPage.tsx
  src/components/Modals/addPlayer.tsx
  src/components/game/game.css
  src/components/game/setPlayers/renderPlayer.tsx
  src/components/game/setPlayers/setPlayers.tsx
  src/models/modal.css
  src/models/modal.tsx
  src/servise/apiServise.ts
  src/store/actions.tsx
  src/store/redusers.tsx
Labels: back-end, enhancement, front-end(JS), should
