Repository VadymSula/mafia-helper, pull requests merged in 2020-05, with the labels that each got.

#88 42 feat/view result game
  guides.html
  src/App.tsx
  src/assets/images/icons_people.png
  src/assets/images/mafia.png
  src/assets/images/mafiaWin.png
  src/assets/images/smile-1.png
  src/assets/images/townWin.png
  src/components/MainPage/mainPage.css
  src/components/MainPage/mainPage.tsx
  src/components/Modals/addPlayer.tsx
  src/components/ResultGame/resultGame.css
  src/components/ResultGame/resultGame.tsx
  src/components/game/game.css
  src/components/game/game.tsx
  src/components/game/inGame/inGame.tsx
  src/components/game/inGame/playerDiv.tsx
  src/components/game/setPlayers/renderPlayer.tsx
  src/servise/apiServise.ts
  src/store/actions.tsx
  src/store/redusers.tsx
  test
Labels: enhancement, front-end(JS), must

#89 79 feat/add logic for major points
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/RatingRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/RatingRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/RatingService.java
  src/main/java/org/deanoffice2/mafiahelper/service/RatingServiceImpl.java
  src/main/resources/db/migration/V1_11_04_2020__create_game_table.sql
  src/main/resources/db/migration/V2_11_04_2020__create_player_result_table.sql
  src/main/resources/db/migration/V3_11_04_2020__create_checks_table.sql
  src/main/resources/db/migration/V4_14_04_2020__create_role_table.sql
  src/main/resources/db/migration/V6_20_04_2020__create_player_table.sql
  src/main/resources/db/migration/V7_22_04_2020__create_club_table_and_add_fk.sql
  src/main/resources/db/migration/V8_22_04_2020__create_rating_table.sql
Labels: back-end, enhancement, must

#91 #73 fix: fixed don`t correct displaying
  src/App.tsx
  src/components/GuidesPage/guidesPage.css
  src/components/GuidesPage/guidesPage.tsx
  src/components/MainPage/mainPage.css
  src/components/ResultGame/post.tsx
  src/store/redusers.tsx
Labels: front-end(JS), front-end(styles)

#92 90 feat/add missing entities and fix rating
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/controller/StaticDataController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/Club.java
  src/main/java/org/deanoffice2/mafiahelper/entity/Person.java
  src/main/java/org/deanoffice2/mafiahelper/entity/Player.java
  src/main/java/org/deanoffice2/mafiahelper/entity/RatingGame.java
  src/main/java/org/deanoffice2/mafiahelper/entity/RoleGame.java
  src/main/java/org/deanoffice2/mafiahelper/repository/RatingRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepository.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/RatingServiceImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticService.java
  src/main/java/org/deanoffice2/mafiahelper/service/StaticServiceImpl.java
  src/main/resources/db/migration/V2_11_04_2020__create_player_result_table.sql
Labels: back-end, bug, enhancement, must

#94 93 fix/fix methods after chsnges in entities
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/GameResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/PlayerResult.java
  src/main/java/org/deanoffice2/mafiahelper/entity/RoleGame.java
  src/main/java/org/deanoffice2/mafiahelper/repository/GameResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/PlayerResultRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/repository/StaticDataRepositoryImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameService.java
  src/main/java/org/deanoffice2/mafiahelper/service/GameServiceImpl.java
  src/main/java/org/deanoffice2/mafiahelper/service/RatingServiceImpl.java
  src/main/resources/db/migration/V1_11_04_2020__create_game_table.sql
Labels: back-end, bug, must

#96 66 fix/fix cut table
  src/components/ResultGame/resultGame.tsx
  src/components/game/inGame/court.tsx
  src/components/game/inGame/inGame.tsx
  src/components/game/inGame/modal.css
  src/components/game/inGame/playerDiv.tsx
  src/models/modal.css
  src/store/actions.tsx
  src/store/redusers.tsx
Labels: bug, front-end(JS), must

#97 80 feat/add logic for extra points
  src/main/java/org/deanoffice2/mafiahelper/controller/GameController.java
  src/main/java/org/deanoffice2/mafiahelper/entity/RatingGame.java
  src/main/java/org/deanoffice2/mafiahelper/service/RatingService.java
  src/main/java/org/deanoffice2/mafiahelper/service/RatingServiceImpl.java
Labels: back-end, enhancement, must

#100 95 fix: fix choice first player in list, if search result is null
  src/components/Modals/addPlayer.tsx
  src/components/game/setPlayers/renderPlayer.tsx
  src/models/modal.css
Labels: bug, front-end(JS), should

#101 98 feat/add select lead
  src/components/GuidesPage/guidesPage.tsx
  src/components/GuidesPage/post.tsx
  src/components/Modals/addPlayer.tsx
  src/components/game/inGame/court.tsx
  src/components/game/inGame/inGame.tsx
  src/components/game/setPlayers/renderPlayer.tsx
  src/components/game/setPlayers/setPlayers.tsx
  src/models/modal.css
  src/store/redusers.tsx
Labels: enhancement, front-end(JS), should

#102 67 fix/result game end
  src/components/ResultGame/resultGame.css
  src/components/ResultGame/resultGame.tsx
  src/components/game/inGame/inGame.tsx
  src/components/game/setPlayers/setPlayers.tsx
  src/store/actions.tsx
  src/store/redusers.tsx
Labels: bug, front-end(JS), must

#105 78 add: added inputs and logic for extra points
  package-lock.json
  package.json
  src/components/ResultGame/resultGame.css
  src/components/ResultGame/resultGame.tsx
  src/components/game/inGame/inGame.tsx
  src/components/game/inGame/modal.css
  src/components/game/setPlayers/setPlayers.tsx
  src/servise/apiServise.ts
  src/store/redusers.tsx
Labels: enhancement, front-end(JS), front-end(styles), must

#109 #107 add: filter: add CORS filter
  src/main/java/org/deanoffice2/mafiahelper/filters/CorsFilter.java
Labels: back-end, enhancement, must
